
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


# OUTPUT_PATH = Path(__file__).parent
# ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Thanasis\build\assets\frame0")


# def relative_to_assets(path: str) -> Path:
#     return ASSETS_PATH / Path(path)

def round_rectangle(x1, y1, x2, y2, radius=25, **kwargs):
        
    points = [x1+radius, y1,
              x1+radius, y1,
              x2-radius, y1,
              x2-radius, y1,
              x2, y1,
              x2, y1+radius,
              x2, y1+radius,
              x2, y2-radius,
              x2, y2-radius,
              x2, y2,
              x2-radius, y2,
              x2-radius, y2,
              x1+radius, y2,
              x1+radius, y2,
              x1, y2,
              x1, y2-radius,
              x1, y2-radius,
              x1, y1+radius,
              x1, y1+radius,
              x1, y1]

    return canvas.create_polygon(points, **kwargs, smooth=True)
window = Tk()

window.geometry("1280x720")
window.configure(bg = "#343747")


canvas = Canvas(
    window,
    bg = "#343747",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    475.0,
    0.0,
    anchor="nw",
    text="Dashboard",
    fill="#16D416",
    font=("Inter", 64 * -1)
)

round_rectangle(
    0.0,
    92.0,
    640.0,
    332.0,
    radius=25,
    fill="#545867",
    outline="white")

round_rectangle(
    0.0,
    332.0,
    640.0,
    575.0,
    radius=25,
    fill="#545867",
    outline="white")

round_rectangle(
    640.0,
    92.0,
    1280.0,
    332.0,
    radius=25,
    fill="#545867",
    outline="white")

round_rectangle(
    640.0,
    332.0,
    1280.0,
    575.0,
    radius=25,
    fill="#545867",
    outline="white")

round_rectangle(
    0.0,
    574.0,
    640.0,
    720.0,
    fill="#555967",
    outline="white")

canvas.create_text(
    43.0,
    606.0,
    anchor="nw",
    text="Total Parked Cars:",
    fill="#16D416",
    font=("Inter", 64 * -1)
)

canvas.create_text(
    198.0,
    269.0,
    anchor="nw",
    text="License Plate:-",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

license_text=canvas.create_text(
    207.0,
    501.0,
    anchor="nw",
    text="License Plate:-",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    847.0,
    262.0,
    anchor="nw",
    text="License Plate:-",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    847.0,
    501.0,
    anchor="nw",
    text="License Plate:-",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    854.0,
    166.0,
    anchor="nw",
    text="Status: Empty",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    854.0,
    406.0,
    anchor="nw",
    text="Status: Empty",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    851.0,
    213.0,
    anchor="nw",
    text="Vehicle Type:-",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    851.0,
    454.0,
    anchor="nw",
    text="Vehicle Type:-",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    198.0,
    173.0,
    anchor="nw",
    text="Status: Empty",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

status_text=canvas.create_text(
    207.0,
    405.0,
    anchor="nw",
    text="Status: Empty",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    204.0,
    221.0,
    anchor="nw",
    text="Vehicle Type:-",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

type_text=canvas.create_text(
    204.0,
    454.0,
    anchor="nw",
    text="Vehicle Type:-",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    884.0,
    337.0,
    anchor="nw",
    text="Spot 4",
    fill="#16D416",
    font=("Inter", 48 * -1)
)

canvas.create_text(
    234.0,
    332.0,
    anchor="nw",
    text="Spot 3",
    fill="#16D416",
    font=("Inter", 48 * -1)
)

canvas.create_text(
    885.0,
    102.0,
    anchor="nw",
    text="Spot 2",
    fill="#16D416",
    font=("Inter", 48 * -1)
)

canvas.create_text(
    232.0,
    102.0,
    anchor="nw",
    text="Spot 1",
    fill="#16D416",
    font=("Inter", 48 * -1)
)

canvas.create_text(
    925.0,
    606.0,
    anchor="nw",
    text="10",
    fill="#FFFFFF",
    font=("Inter", 64 * -1)
)
window.resizable(False, True)

